# Generated by Django 5.2.11 on 2026-02-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(upload_to='featured_images/', null=True, blank=True),
        ),
    ]
