# Generated by Django 5.2.11 on 2026-02-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ThoughtNest', max_length=100)),
                ('site_tagline', models.CharField(default='Gather ideas. Grow perspectives.', max_length=200)),
                ('site_description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('posts_per_page', models.PositiveIntegerField(default=12)),
                ('excerpt_length', models.PositiveIntegerField(default=25)),
                ('allow_comments', models.BooleanField(default=True)),
                ('moderate_comments', models.BooleanField(default=False)),
                ('allow_registration', models.BooleanField(default=True)),
                ('show_author', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
