# Generated by Django 5.2.11 on 2026-02-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
